name: asciicker # you probably want to 'snapcraft register <name>'
base: core18 # the base snap is the execution environment for this snap
version: 'y6' # just for humans, typically '1.2+git' or '1.3.2'
summary: 3D textmode RPG prototype # 79 char long summary

description: |
  This is WIP (work in progress) of 3D textmode RPG (role playing game) prototype.
  Project has started in 2017, initially written in javascript and targetting only web.
  In 2019 development changed to C++ language and now it is targetting almost anything.
  Currently builds are provided for linux, windows and web.

#architectures:
#  - build-on: s390x
#    run-on: s390x
#  - build-on: ppc64el
#    run-on: ppc64el
#  - build-on: arm64
#    run-on: arm64
#  - build-on: armhf
#    run-on: armhf
#  - build-on: amd64
#    run-on: amd64
#  - build-on: i386
#    run-on: i386

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

apps:
  font-6:
    command: setfont $SNAP/fonts/cp437_6x6.png.psf
  font-8:
    command: setfont $SNAP/fonts/cp437_8x8.png.psf
  font-10:
    command: setfont $SNAP/fonts/cp437_10x10.png.psf
  font-12:
    command: setfont $SNAP/fonts/cp437_12x12.png.psf
  font-14:
    command: setfont $SNAP/fonts/cp437_14x14.png.psf
  font-16:
    command: setfont $SNAP/fonts/cp437_16x16.png.psf
  font-18:
    command: setfont $SNAP/fonts/cp437_18x18.png.psf
  font-20:
    command: setfont $SNAP/fonts/cp437_20x20.png.psf
  font-24:
    command: setfont $SNAP/fonts/cp437_24x24.png.psf
  font-28:
    command: setfont $SNAP/fonts/cp437_28x28.png.psf
  font-32:
    command: setfont $SNAP/fonts/cp437_32x32.png.psf
  term:
    command: ./game_term
  x11:
    command: ./game
  edit:
    command: ./asciiid
  server:
    command: ./server

parts:

  game-term:

    build-packages:
      - g++
      - make
      - libgpm-dev

    stage-packages:
      - gpm
      - libgpm2
      - kbd

    source: .
    plugin: nil
    override-build: |
      make -f makefile_game_term
      cp .run/game_term $SNAPCRAFT_PART_INSTALL

  game:

    build-packages:
      - g++
      - make
      - libgpm-dev
      - xorg-dev
      - libgl1-mesa-dev

    stage-packages:
      - gpm
      - libgpm2
      - libx11-6
      - libx11-data
      - libxinerama1
      - libgl1-mesa-glx
      - kbd

    source: .
    plugin: nil
    override-build: |
      make -f makefile_game
      cp .run/game $SNAPCRAFT_PART_INSTALL

  asciiid:

    build-packages:
      - g++
      - make
      - xorg-dev
      - libgl1-mesa-dev

    stage-packages:
      - libx11-6
      - libx11-data
      - libxinerama1
      - libgl1-mesa-glx

    source: .
    plugin: nil
    override-build: |
      make -f makefile_asciiid
      cp .run/asciiid $SNAPCRAFT_PART_INSTALL

  server:

    build-packages:
      - g++
      - make

    source: .
    plugin: nil
    override-build: |
      make -f makefile_server
      cp .run/server $SNAPCRAFT_PART_INSTALL

  assets:

    plugin: nil
    override-build: |
      
      mkdir $SNAPCRAFT_PART_INSTALL/a3d
      cp a3d/game_map.a3d $SNAPCRAFT_PART_INSTALL/a3d

      mkdir $SNAPCRAFT_PART_INSTALL/fonts
      cp fonts/* $SNAPCRAFT_PART_INSTALL/fonts

      mkdir $SNAPCRAFT_PART_INSTALL/sprites
      cp sprites/*.xp $SNAPCRAFT_PART_INSTALL/sprites

      mkdir $SNAPCRAFT_PART_INSTALL/icons
      cp icons/app.png $SNAPCRAFT_PART_INSTALL/icons

      mkdir $SNAPCRAFT_PART_INSTALL/meshes
      cp meshes/*.akm $SNAPCRAFT_PART_INSTALL/meshes

      mkdir $SNAPCRAFT_PART_INSTALL/palettes
      cp palettes/*.png $SNAPCRAFT_PART_INSTALL/palettes
